/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package e.luwas;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class adwindow extends javax.swing.JFrame {
   
    public adwindow() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        search = new javax.swing.JButton();
        p = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        dis1 = new javax.swing.JTextArea();
        re = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        search.setBackground(new java.awt.Color(0, 204, 204));
        search.setFont(new java.awt.Font("Bebas", 1, 24)); // NOI18N
        search.setForeground(new java.awt.Color(255, 255, 255));
        search.setText("search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jPanel1.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 290, 100, 60));

        p.setBackground(new java.awt.Color(0, 204, 102));
        p.setFont(new java.awt.Font("Bebas", 1, 24)); // NOI18N
        p.setForeground(new java.awt.Color(255, 255, 255));
        p.setText("print");
        p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pActionPerformed(evt);
            }
        });
        jPanel1.add(p, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 200, 100, 70));

        dis1.setBackground(new java.awt.Color(51, 51, 51));
        dis1.setColumns(20);
        dis1.setFont(new java.awt.Font("Bebas", 1, 18)); // NOI18N
        dis1.setForeground(new java.awt.Color(255, 255, 255));
        dis1.setRows(5);
        jScrollPane1.setViewportView(dis1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 550, 380));

        re.setBackground(new java.awt.Color(255, 204, 204));
        re.setFont(new java.awt.Font("Bebas", 1, 24)); // NOI18N
        re.setForeground(new java.awt.Color(255, 255, 255));
        re.setText("remove");
        re.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reActionPerformed(evt);
            }
        });
        jPanel1.add(re, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 370, 100, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/admindata.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pActionPerformed
    
    
    try (BufferedReader br = new BufferedReader(new FileReader("vlist.txt"))) {
    String line;
    
    while ((line = br.readLine()) != null) {
        dis1.append(line + "\n");
    }
} catch (IOException e) {
    e.printStackTrace();
}   
      
    }//GEN-LAST:event_pActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
       
     
        dis1.setText("");
        String fileName = "vlist.txt";
        String searchString = JOptionPane.showInputDialog("Enter Search Data: ");
        if(searchString.isEmpty()){
            JOptionPane.showMessageDialog(null, "Input Data!");
        }
        
        String line = null;

        try {
            FileReader fileReader = new FileReader(fileName);
            BufferedReader bufferedReader = new BufferedReader(fileReader);

            while((line = bufferedReader.readLine()) != null) {
                if (line.contains(searchString)) {
                    
                    dis1.append("\n"+line);
                }
            }        
            bufferedReader.close();
        } catch(IOException ex) {
             JOptionPane.showMessageDialog(null, "Unable to open file '" + fileName + "'");
        }
  
    }//GEN-LAST:event_searchActionPerformed

    private void reActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reActionPerformed
     
        try (FileWriter fw = new FileWriter("vlist.txt", true)) {
            fw.write("");
            JOptionPane.showMessageDialog(null, "Successfully Removed!");
            dis1.setText("");
        } catch (IOException e) {
                e.printStackTrace();
    }//GEN-LAST:event_reActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adwindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adwindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adwindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adwindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adwindow().setVisible(true);
            }
        });
    }
    visitorList vlist = new visitorList();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea dis1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton p;
    private javax.swing.JButton re;
    private javax.swing.JButton search;
    // End of variables declaration//GEN-END:variables
}
